[package]
name = "loid-agent"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tokio.workspace = true
loid-transport.workspace = true
tonic.workspace = true
