[package]
name = "loid-resources"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]

[dev-dependencies]
# testing
testcontainers.workspace = true
testcontainers-modules.workspace = true
tokio.workspace = true