[package]
name = "loid-sensors"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
loid-events.workspace = true
tokio-cron-scheduler.workspace = true
chrono.workspace = true
serde.workspace = true