[package]
name = "loid-events"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
uuid.workspace = true
chrono.workspace = true
serde.workspace = true


[dev-dependencies]
serde_json.workspace = true