/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Impact {
  Negligible = 'Negligible',
  Minor = 'Minor',
  Moderate = 'Moderate',
  Significant = 'Significant',
  Severe = 'Severe'
}
export const enum Urgency {
  Low = 'Low',
  Medium = 'Medium',
  High = 'High',
  Critical = 'Critical'
}
export const enum Priority {
  Low = 'Low',
  Medium = 'Medium',
  High = 'High',
  Critical = 'Critical'
}
export interface Source {
  system: string
  sourceId?: string
}
export type JsEvent = Event
export declare class Event { }
export type JsEventBuilder = EventBuilder
export declare class EventBuilder {
  constructor(system: string, sourceId?: string | undefined | null)
  withCorrelationId(correlationId: string): this
  withPriority(priority: Priority): this
  withImpact(impact: Impact): this
  withUrgency(urgency: Urgency): this
  build(): Event
}
