/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Impact {
  NEGLIGIBLE = 'NEGLIGIBLE',
  MINOR = 'MINOR',
  MODERATE = 'MODERATE',
  SIGNIFICANT = 'SIGNIFICANT',
  SEVERE = 'SEVERE'
}
export const enum Urgency {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}
export const enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}
export interface Source {
  system: string
  sourceId?: string
}
export type JsEvent = Event
export declare class Event { }
export type JsEventBuilder = EventBuilder
export declare class EventBuilder {
  constructor()
  withCorrelationId(correlationId: string): this
  withPriority(priority: Priority): this
  withImpact(impact: Impact): this
  withUrgency(urgency: Urgency): this
  build(): Event
}
